name = "DLProteinFormats"
uuid = "df93d313-1126-4eb6-ac29-b325d5898587"
version = "0.1.11"
authors = ["murrellb <murrellb@gmail.com> and contributors"]

[deps]
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HuggingFaceApi = "3cc741c3-0c9d-4fbe-84fa-cdec264173de"
MergedArrays = "4201acb4-6ad2-4fbc-ab19-c24116385dd7"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
ProteinChains = "b8e8f2a5-48d3-44f1-ba0d-c71cb7726ff8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticStrings = "4db0a0c5-418a-4e1d-8806-cb305fe13294"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[sources]
ProteinChains = {rev = "main", url = "https://github.com/MurrellGroup/ProteinChains.jl"}

[compat]
BioStructures = "4.6.0"
CSV = "0.10.15"
DataFrames = "1.8.1"
Graphs = "1.13.2"
HuggingFaceApi = "0.1.0"
MergedArrays = "0.3.0"
OneHotArrays = "0.2.10"
PeriodicTable = "1.2.1"
ProteinChains = "0.7"
Random = "1"
Serialization = "1"
StaticArrays = "1.9.14"
StaticStrings = "0.2.6"
StatsBase = "0.34"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
